package elseif;

import javax.swing.JOptionPane;

public class Horoscope {
public static void main(String[] args) {
	
	String SSign = JOptionPane.showInputDialog("What is your star sign");
	
if (SSign.equalsIgnoreCase("aries")) {
		JOptionPane.showMessageDialog(null, "The symbol for this sign is that of a ram for good reason. \n Aries is full of life and possesses high energy, which makes this sign always looking for a challenge. \n The typical Aries person is full of vitality, curiosity, and has a heightened sense of justice. \n  They often excel at anything where a bit of competition is involved, whether this is of a cognitive nature or physical.  \n The challenge is the thing. If there is a chance to win, to best someone, to show off abilities, Aries is in it to win it. \n  The Aries person feels most alive when they are in control and leading others. \n  They are often impatient and abrupt with those whom they feel are not their equals and are in a leadership position.\n Most Aries do not like being told what to do if the person in charge is less talented than they." +

"\n Aries is a fire sign which means that they tend to have the characteristics of fire: warm, vital, and bright. They can sometimes be impulsive and have hot tempters. \n However, they have a deep desire to protect and when they have harmed someone in error they will be the first to make amends. \n They are optimistic and are not given to depressive interludes");
	}else if (SSign.equalsIgnoreCase("taurus")) {
		JOptionPane.showMessageDialog(null, "Tarus’s symbol is the bull because this sign’s characteristic is to be peaceful and methodical. This sign is often very deliberate in their actions, relaxed, and enjoys all of the sensual pleasures that abound in this dimension. Food, drink, luxury, are all sought after by the typical taruean. Because this sign loves luxury they are willing to work hard to obtain it. They are slow to anger, but once disturbed it can be volatile. Taurus signs look for stability in their lives and in their partners and co-workers. Taurus people are not in a hurry, typically, and it can take them many years to decide what it is that they would like to do for a living, or where they’d like to go on vacation. Many of this sign prefer to live in the country as they are drawn to the earth and the natural world. Earth signs tend to have solid, reputable natures, which coincides with the Earth.\r\n" + 
				"Additionally, this sign takes a long time to fully commit to a relationship, but once they do they are in it for the long haul. Most Taurus males marry for life and are dedicated companions, parents, and lovers. Female Taurus are like male Taurus in that once they commit themselves to a relationship they are stubborn and slow to leave it. However, if Taurus women feel put upon, taken for granted, or unappreciated for long enough, they will leave.\r\n" 
				);
	}else if (SSign.equalsIgnoreCase("gemini")) {
		JOptionPane.showMessageDialog(null, "The Gemini symbol is that of a pair of twins. This is because this sign rarely likes to do anything alone. Gemini are never happier than when they are sharing ideas and concepts with someone else. Communication is a key element for this sign, so many of this sign go into occupations that include some communication in some large capacity. Curiosity is a key characteristic of this sign, and they are people persons. Gemini are great at parties because they can find almost anything to talk about with anyone. Gemini are adventurous by nature and so engage in traveling as often as they can as it affords them the opportunity to meet new people, experience new ideas, and to learn new concepts.\r\n" + 
				"\r\n" + 
				"Gemini are air signs, which means that they have light, airy personalities, with an effervescence that seems to draw people to them. This sign craves intellectual stimulation and often will push the envelope physically, mentally, and spiritually. If someone were to live out the book, Eat, Pray, Love it would be this sign as they are gluttons for new experiences, sometimes out of the box and out of the way experiences and people. This sign is also incredibly creative and are given to giant leaps of intuition, which makes them great entrepreneurs, designers, writers, speakers, and anything artistic. They love bright vibrant colors.\r\n" + 
				"\r\n" + 
				"Upside: Gemini are great conversationalists, and are charming people. Interesting to speak with, Gemini know a little bit about a lot of things. They have a great sense of humor and are generally optimistic people. Gemini often make their own fun, despising boredom.\r\n" + 
				"\r\n" + 
				"Downside: Gemini like to be the center of attention; always. When they perceive the situation to not be in their favor, they leave it. This can include relationships, careers, and friendships. Because of this need to be seen as important, Gemini will sometimes stretch the truth. When they are focused only on themselves they can be largely unsympathetic and rude. Male Gemini tend to change jobs often, and female Gemini change partners often due to boredom.\r\n" + 
				"\r\n" + 
				"Libra and Aquarius are also air signs.");
	}else if (SSign.equalsIgnoreCase("cancer")) {
		JOptionPane.showMessageDialog(null, "The crab symbolizes this sign for good reason. Just as the crab carries its own shell on its back, so too, does the typical cancerian…so to speak. The typical cancer person is all about home and family and is very dedicated and loyal to friends and family. Crabs often move sideways instead of moving in a straight line, and so will the person of this sign. Often, if it will avoid a fight, or achieve the goal, then moving in alternative directions to arrive at the destination is typical. They tend to grasp and hold tightly those things that make them happy, and never let go. The key characteristic of this sign is that Cancer people need to be needed. They need to know that they matter to someone and that they are secure in that love. Brave, courageous, protective, all describe the best possible traits of this sign. Shy, reserved, brooding, and moody, do not serve the cancer person well, but may surface if their needs are not being met\r\n" + 
				"\r\n" + 
				"Cancer is a water sign which means that they have a deep, mysterious side to them that can also be gentle and nurturing.");
	}else if (SSign.equalsIgnoreCase("leo")) {
		JOptionPane.showMessageDialog(null, "The lion is the symbol for this sign because the lion embodies the best characteristics of the leo; proud, regal, relaxed, and in charge. Leo people know they are in charge, even when it may seem outwardly that they are not.\r\n" + 
				"\r\n" + 
				"Leo signs tend to like relaxation, preferably someplace warm and comfortable. Leo likes the big picture, not the small details and fine print. Things that are too complicated, involved, or boring, they have no patience for. They are natural leaders and don’t often do well in situations where they have to take orders from others.\r\n" + 
				"\r\n" + 
				"Love is king to a leo. To love and be loved is a driving motivation for this sign. Leos, not unlike the lion of a pride, need to be adored. If they are ignored or go unrecognized for some contribution they will feel hurt. All leos like to know that they have been seen and appreciated.\r\n" + 
				"\r\n" + 
				"Fire signs, like Leo, are warm, bright individuals that use that energy and warmth to draw people to them. When the right balance is struck with a leo, those around this sign will feel as loved and appreciated as the leo in their midst.\r\n" + 
				"\r\n" + 
				"Upside: Leo tend to be honest and decent people, opting to do the right thing regardless of the situation. They love organization so that they can find their ‘things’. Leos love material goods and luxury and want those that they love to experience this wealth as well. Leo are generally accepting of everyone initially and make decent, lasting relationships.\r\n" + 
				"\r\n" + 
				"Downside: Leo have a great sense of self-worth which can cross the line into arrogance. Leo can tend toward extravagance if they are not satisfied with what they have. Because they like to be in charge, they can often become smothering to their mates and friends, which may leave them alone (which Leo hates). Divorce and loss are devastating to this sign as they are all about the community and family.\r\n" + 
				"\r\n" + 
				"Leo is a fire sign, like Aries and Sagittarius.");
	}else if (SSign.equalsIgnoreCase("virgo")) {
		JOptionPane.showMessageDialog(null, "The cool, calm, clarity that this sign exudes is why the symbol of the Maiden was chosen. Virgo people are mild mannered on the surface, but underneath there is a flurry of activity. Their minds are never quiet; always thinking, calculating, assessing. They loves making something out of nothing, nurturing and growing small things. They tend to be extremely detail oriented and particularly like producing something that is not only useful, but beautiful and skillful.\r\n" + 
				"\r\n" + 
				"Virgo don’t mind being alone as long as they know that they are appreciated and needed. They are sympathetic listeners, and are ready to help out those in need. Their good nature often makes them easy to take advantage of, and often they end up taking on more jobs and tasks than they should. This sign would do well to carefully consider the situation and the task before agreeing to take it on.\r\n" + 
				"\r\n" + 
				"Virgo is an Earth sign which means that they love making something from the land with their own hands. They do not tend to be loud or bossy, but are brilliant strategists and an asset to any team. Very often they will overburden themselves and take on more than they should, which makes their work suffer.");
	}else if (SSign.equalsIgnoreCase("libra")) {
		JOptionPane.showMessageDialog(null, "Libra people tend to need balance in their lives like no other sign of the zodiac, which makes the symbol of the scales particularly appropriate for this sign. Libra people need to keep a balance between work lives and recreational lives and an equal balance in their emotional and spiritual/physical lives. Because of this need Libra signs can sometimes seem wishy-washy when they are asked to make a decision. This is because they must ‘weigh’ all of their options. However, rest assured, that when a Libra makes up their mind the decision is likely to be the best win/win for all involved; benefiting the most people. This sign does not like to see people unhappy.\r\n" + 
				"\r\n" + 
				"Harmony and peace are key to making this sign happy. When things are balanced, then there is harmony. This sign is often charming and people like to be around them and the only time that they will become unhappy is when they perceive that they have been treated unfairly. This sign does really well to embrace some form of meditation as it allows them to find that internal balance that will allow the outer balance to manifest itself. Most Libra enjoy physical exercise that involves some mental component, such as long distance running, or yoga. Many run marathons.");
	}else if (SSign.equalsIgnoreCase("scorpio")) {
		JOptionPane.showMessageDialog(null, "The symbol for Scorpio is the scorpion. This creature was chosen because it typifies many of the characteristics of this sign. The scorpio person is not necessarily aggressive on its own, unless provoked and in general would rather be contemplative. They crave alone time and often become extremely annoyed when they don’t get it. Scorpio people are great secret keepers and feel each emotion more intensely than other signs. Perhaps because of this they are able to be quite discerning when assisting people with their problems. They are able to cut to the bottom line and show others the best and the worst in their lives.\r\n" + 
				"\r\n" + 
				"Scorpio signs are not fearful individuals, often trying things that others would not attempt. This is because they most often become self-aware at an earlier age than most other signs. This also gives them a custodial feel toward other signs and they have an inflamed sense of justice when it comes to standing up for those who lack that ability. Scorpio signs are very interested in what makes people tick on the inside and are often in fields that allow them to discover things about the internal workings of others.\r\n" + 
				"\r\n" + 
				"Upside: Scorpio exhibit extreme self-control in many areas, and as a result expect that of those around them. They are disciplined, protective and are very interested in others. They give of themselves but do expect the same in return. Scorpio males and females both need to be the leaders, and excel at problem solving and troubleshooting projects and situations.\r\n" + 
				"\r\n" + 
				"Downside: Scorpio invented the term ‘vendetta’. Once a Scorpio is crossed, they don’t forget it. Female Scorpio are worse about this than they others, often going decades without making amends with friends and family. Scorpio also tend to be pessimistic, often seeing threats where there aren’t any, which can make them suspicious, stubborn and paranoid without cause.\r\n" + 
				"\r\n" + 
				"Scorpio is a water sign, like Cancer and Pisces.");
	}else if (SSign.equalsIgnoreCase("sagittarius")) {
		JOptionPane.showMessageDialog(null, "The centaur is the symbol for this sign. In mythology, the centaur was half man and half horse, given to pursing pleasure. The centaur is shown with a bow, which he shoots. Wherever the arrow lands, the centaur follows, retrieves the arrow and shoots again. Those born under this sign will love travelling, discovering new things, meeting new people, and learning new things.\r\n" + 
				"\r\n" + 
				"Sagittarians crave the freedom of the open road, both metaphorically and physically. They are most unhappy when they are tied to a normal routine and can become restless in situations where there is not enough variety involved. Because they travel so much and are eager to experience new things, those of this sign are fun to be around and often have large numbers of friends. They question everything and think that everyone should do the same.");
	}else if (SSign.equalsIgnoreCase("aquarius")) {
		JOptionPane.showMessageDialog(null, "The man who carries the pitcher of water is the symbol for this sign. This is because Aquarians are often generous with their time and resources. For this reason this sign often find themselves in occupations where they are helping on some humanitarian level. They are interested and have a deep concern for the welfare of others. They never know a stranger and are generally loved by all around them. Aquarians never meet a stranger and often will go out of their way to meet with people that they’ve not heard from for years. Connection is at the core of this sign.\r\n" + 
				"\r\n" + 
				"Fascinated by all things gadget, many Aquarians enjoy tinkering with inventions and processes. On the surface, Aquarius people are often not very emotional, because they are more concerned with the exchanging of ideas and how they might better assist someone in their cause. Aquarians have a great deal of patience and tolerance for their fellow man. They make excellent teachers and relief aid workers, though do not become personally involved with them.");
	}else if (SSign.equalsIgnoreCase("pisces")) {
		JOptionPane.showMessageDialog(null, "The fish is the symbol given to this sign, primarily because fish live in a secretive and mysterious place. Pisces tend to be daydreamers, often dreaming up brilliant ideas and plans which they are unable to facilitate themselves. They have a happy and vibrant inner life that few get to share or see. They are deeply caring about others and don’t like to see people become unhappy.\r\n" + 
				"\r\n" + 
				"They are tremendously dedicated individuals, staying with companies for decades where others move from one job to the next. So, too, with relationships. Others may find Pisces difficult to get to know because they don’t often readily share their underlying passion and compassion. Pisces signs tend to be highly and deeply religious, and sometimes will go overboard with their devotion to their particular faith. This can also lead to intolerance and bigotry.");
	}else if (SSign.equalsIgnoreCase("Capricorn")) {
		JOptionPane.showMessageDialog(null, "The mountain goat is the symbol for this sign because of the characteristic of the goat to climb higher and higher without losing his footing. Capricorn people are the type that are goal oriented and driven to succeed despite all odds. They will work long and hard hours toward a purposeful goal. Self-disciplined and successful, it is no wonder that some of the world’s greatest scientists, leaders, and teachers have been Capricorn.\r\n" + 
				"\r\n" + 
				"Achievement is everything to a Capricorn. For this reason they tend to take life very seriously and are not tolerant of those who do not. They are also very good at state’s craft engaging in mental parrying at a high level. They are natural born leaders, politicians, mathematicians, and diplomats. Capricorn people tend to guard their hearts closely and well. To get close to a Capricorn may take some time, but once achieved, well worth it.");
	}
}
}
